From: charles@rebelbase.com
Newsgroups: alt.test
Subject: Collision - three attachments, one filename
Organization: Lazars Android Works
Lines: 687
Message-ID: <collision>
Date: Wed, 02 May 2001 04:17:10 GMT

begin 644 collision
M5&AI<R!I<R *9FEL92!N=6UB97(@;VYE+@I)=',@;F%M92!I<PH*(" @(" @
-($-/3$Q)4TE/3@H*"B!N
 
end
begin 644 collision
M"E1H:7,*"6ES"@D)9FEL90H)"0EN=6UB97(*"0D)"71W;RX*"@I)=',@;F%M
692!I<R!A;'-O(&!C;VQL:7-I;VXG"FUB
 
end
begin 644 collision
M"@H*"@H*"@H*"@D)"0D)5&AI<R!I<R!F:6QE(&YU;6)E<B!T:')E92X@($ET
5<R!N86UE(&ES(&-O;&QI<VEO;BX*
 
end
