From: charles@rebelbase.com
Newsgroups: alt.test
Subject: Penguin
Organization: Lazars Android Works
Lines: 687
Message-ID: <penguin_2_2>
Date: Wed, 02 May 2001 04:17:10 GMT

M78W6-3R!$)A``CRD`OA!!$C!R)R),)Y24%`")W",?8E&-O#^P2S,0`8XHP84
MVX+=7DQ*Y?X$5DIJ``B47SW\FA;]U>0YF7-])2'*Y("15DJIP$-60#.HY6K9
M$H%X@0U0@@08T&4\1?X1A*Q4AB:@@`T$`BQPP`BY%$6X@Q3@Y9#5@T&EXGH!
M'P-*I6.NGS^B%21=P56>%C^47TC,(K`)&W$MU?Y\W_<9I""RWP7:E9T)01U8
M)@*`P#L0PPS`@!2T4]=0DZ!\T-BXIGD*$FQF!5(Z0P1@0S,4CTOF'`8*IA=)
M)56BE7`"&QI$@7&6!'SQ6>_Y%6"Q4$,A7',^)U1"8EF)%IX)U7N!@`(X`2W,
MP@1`7'I>J$?<)0PLY3L@F7]9VF[^?F%A)=<_LMA#BH$?]"=*Z)-6WIM/$5?4
MQ=YR=9$%:IF-9A]D=IF=`><%&&8];"<MW$$53$!+8:B14H0R;J@?-`.2N8%?
M$N@MMB*.,M6=D9Q074&]'0$:O(,UJ.A*#-H^]1.`NH&\(=IPS9G)"2ACREZ-
MFJ%@>F4&SF0D\A8LYJ0&((`8*$`.^`$VW,$L5`%V':F12L$$;"@!Y$`]Z%.`
M(I-A12GSX*CKB6A@`:>)VL.>U4.*>NE+*`"G*D`]?&JB#EIP%1.`)B>]V=I1
MH:F:5JER66!O,I-):E_CE1:-H0&$-L.>!BD,`*J@"NIL5D$$T`(Q>&HQ'9J`
M$BB";I_^8S;8G0'GG-F#I>X9"#B!IAZ&$^1`#C1#,[S#.WAJHH;JGVDIGXTK
M@"HFO@V77\$H<SKGLBK;+2I7K4EK/>AI#A`#`<Q`!,#`!`1JK\*F;/)!%>0E
M`33#IP;7H:$K8"D3NS88E;+07P6GI8[KGS5#M5I'!CC!M6JKIWIKP1:LJ/X9
M,9W0":&;O`T56JUIF]YBW#1LR<V8O.*JO6+##-S!KO*!A?9K>DJ!#A3J#!``
M,32#IS:I3\6HHHU6"]E9LP;GO.DG",RK`F!#Q?:(-1```?@!,5PKMF*KMFYM
MIWKJD>F3K_64F::I8!7>8-5:CVHI&LQK,]@K`=`"ON[JOHK^!G\`0"S8[51D
M@PX`;`3,`#%D:]`6JW*JZ9I:J=*Z;(W9ZKQ*:#5$[;!$`!#0`BU@`]56+3'X
M`=9F*[=RJAB`;)CVTT$)FYG.6;SMVFDU+;:Z[0S,;+Y6`1]@E^7L+<_Z+."&
M:M@&&[[E+KZAVY[QDXW)EP(T0P8`@>.>317`P"S<P0Q,;N5B;L9N:[=&0134
M0^>"*3%=K^+.:^I6[NK>@9_JZ^LRQ_#PP00$;,\2P\]R*KBRJ.^2J^_ZV9]Q
M*J[R:004KQ7UP_$F[_)2K=5FKK9R*[=N;=:BK]O>Z\Q^K[Y.`#LL$CN0[_'N
M[]\";:>"ZI]1KZ@FJGS-*[?F@!/:^(&0VJ^!E6\$]*WD4BXV8(,?5&X!5R[5
MKNX!S\*NNNX"ZQ0?.#`,**_E8NL[`&VW=JT/!Z\37*[,?C`(UUSYYN\L1(#W
M*J\+=^\2(_"03H`.1%H-VW#R3JX?9/'?9FV]7FT'8T.01@`,]T,1JRCYEB\,
M("\,IW$,1_$$U+#N[>T95T'`)K$2>R_KCO`L_&D_\$$9%S$?[*T."++]5K$A
M'_(?)[(B+S(C-[(C/S(D1[(D3S(E5[(E7S(F9[(F;S(G=[(G?S(HA[(HCS(I
0E[(IGS(JI[(JK[)A!`0`.P``
`
end

la la la
