Path: e3500-chi1.usenetserver.com!e420r-sjo4.usenetserver.com!cyclone2.usenetserver.com!news-out.usenetserver.com!newsfeed2.earthlink.net!newsfeed1.earthlink.net!newsfeed.earthlink.net!logbridge.uoregon.edu!leto.backbone.ou.edu!news.ou.edu!not-for-mail
Message-ID: <two_uu_attachments>
From: Charles Kerr <charles@rebelbase.com>
Subject: uu attachment test
Newsgroups: alt.test
Date: Wed, 2 May 2001 14:17:22 -0500

Two uu attachments in this post: foo_01.txt and foo_02.txt

begin 644 foo_01.txt
D5&AI<R!I<R!T:&4@8F]D>2!O9B!M97-S86=E(")F;V\@,2(*
`
end

begin 644 foo_02.txt
D5&AI<R!I<R!T:&4@8F]D>2!O9B!M97-S86=E(")F;V\@,B(*
`
end
