const char * fallback_post_ui = 
"<ui>\n"
"  <menubar name='post'>\n"
"    <menu action='file-menu'>\n"
"      <menuitem action='post-article' />\n"
"      <separator />\n"
"      <menuitem action='save-draft' />\n"
"      <menuitem action='open-draft' />\n"
"      <separator />\n"
"      <menuitem action='close' />\n"
"    </menu>\n"
"    <menu action='edit-menu'>\n"
"      <menuitem action='cut' />\n"
"      <menuitem action='copy' />\n"
"      <menuitem action='paste' />\n"
"      <menuitem action='rot13' />\n"
"      <separator />\n"
"      <menu action='charsets-menu'>\n"
"        <placeholder name='charset-list' />\n"
"      </menu>\n"
"      <menuitem action='remember-charset' />\n"
"      <separator />\n"
"      <menuitem action='manage-profiles' />\n"
"      <separator />\n"
"      <menuitem action='run-editor' />\n"
"      <menu action='editors-menu'>\n"
"        <placeholder name='editor-list' />\n"
"      </menu>\n"
"      <menuitem action='manage-editors' />\n"
"      <separator />\n"
"      <menuitem action='wrap' />\n"
"      <separator />\n"
"      <menuitem action='spellcheck' />\n"
"    </menu>\n"
"  </menubar>\n"
"\n"
"  <toolbar name='post-toolbar'>\n"
"    <toolitem action='post-article' />\n"
"    <separator />\n"
"    <toolitem action='save-draft' />\n"
"    <toolitem action='open-draft' />\n"
"    <separator />\n"
"    <toolitem action='wrap' />\n"
"    <separator />\n"
"    <toolitem action='rot13' />\n"
"    <toolitem action='run-editor' />\n"
"  </toolbar>\n"
"\n"
"</ui>\n";
